install.packages("spdep")
install.packages("spatstat")
install.packages("GISTools")
install.packages("rgdal")
install.packages("maptools")
install.packages("RColorBrewer")
install.packages("GWmodel")
install.packages("e1071)")